# Generated by Django 3.2.8 on 2022-01-13 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0004_alter_tweet_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='image_delete_hash',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
