# Generated by Django 3.2.8 on 2022-01-13 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0006_alter_tweet_image_delete_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='image_delete_hash',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
